apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: ${DESTINATION_SECRET_NAME}
  namespace: ${CLUSTER_SECRETS_NAMESPACE}
spec:
  updatePolicy: Replace
  deletionPolicy: Delete
  refreshInterval: 1h
  secretStoreRefs:
    - name: backend
      kind: ClusterSecretStore
  selector:
    secret:
      name: ${SOURCE_SECRET_NAME}
  data:
    - match:
        secretKey: ${SECRET_KEY}
        remoteRef:
          remoteKey: ${DESTINATION_SECRET_NAME}
          property: ${PROPERTY}
