apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-reader
  namespace: cluster-secrets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eso-secret-reader
  namespace: cluster-secrets
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eso-secret-reader
  namespace: cluster-secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: eso-secret-reader
subjects:
- kind: ServiceAccount
  name: eso-reader
  namespace: cluster-secrets
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: backend
spec:
  provider:
    kubernetes:
      remoteNamespace: cluster-secrets
      server:
        url: "https://kubernetes.default.svc"
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: cluster-secrets
      auth:
        serviceAccount:
          name: eso-reader
          namespace: cluster-secrets
